name: Build wheels, source distribution and publish to Gemfury

# Source: https://raw.githubusercontent.com/pypa/cibuildwheel/main/examples/github-deploy.yml

env:
  # Only build for CPython 3.10+
  CIBW_BUILD: "cp*-manylinux_x86_64"
  CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-*"

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  publish_gemfury:
    name: Publish package to Gemfury
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          user: ${{ secrets.GEMFURY_TOKEN }}
          repository-url: ${{ secrets.PACKAGE_REGISTRY_URL }}
          verbose: true
